services:
  - type: web
    name: ecoversa-web-app
    runtime: static
    buildCommand: ./build.sh
    staticPublishPath: ./web-app/dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html